server:
  port: 8088

spring:
  application:
    name: reporting-service
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

jwt:
  secret: ${JWT_SECRET}